env:
  es6: true
  node: true
extends:
  - standard
  - plugin:jest/all
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - jest
rules:
  semi:
    - 2
    - always
