version: "3"

services:
  app: # services name
    build: . # Build the current dir
    command: npm run dev
    environment:
      NAME: name # Env variable example
    depends_on:
      - db
    ports:
      - "3000:3000" # Expose from my machine the port to the container port
    volumes:
      - .:/usr/src # Use volumes to override the files in the container
      - /usr/src/node_modules  # Don't override the node_module in the container
  db:
    image: postgres:11.7
