version: "3"

services:
  app: # services name
    build: . # Build the current dir
    command: npm run dev
    container_name: app
    environment:
      PGHOST: db
      PGUSER: ${PGUSER}
      PGDATABASE: ${PGDATABASE}
      PGPASSWORD: ${PGPASSWORD}
      PGPORT: ${POSTGRES_PORT}
    depends_on:
      - db
    ports:
      - "3000:3000" # Expose from my machine the port to the container port
    volumes:
      - .:/usr/src # Use volumes to override the files in the container
      - /usr/src/node_modules  # Don't override the node_module in the container
  db:
    image: postgres:11.7
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - ${PORT}:${POSTGRES_PORT}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "5555:80"
    restart: unless-stopped
